<?php

declare(strict_types=1);

namespace Funnypot\App\Tarpit;

use Funnypot\App\AiApi\StreamEmitter;

/**
 * The tarpit generator core (FP-0245a): deterministic, offset-addressable fake bytes at O(block)
 * memory, independent of the artifact's logical size. This is the enabler the whole tarpit rests on
 * — a 2-million-line log or an 8 MiB export is fabricated block-by-block and streamed, so a worker
 * never materialises the body (the exact asymmetry the ticket demands: cheap for us to emit,
 * expensive for an attacker to ingest/reason over).
 *
 * It mirrors two seams already in the tree:
 *   - {@see \Funnypot\Core\Support\Fake\FakeSecrets}::chars() hash-chains per-block sha256 to expand
 *     any length from hash()/substr() alone;
 *   - {@see \Funnypot\App\Http\DownloadRouter}::fill()/fallbackChunks() base64s per-seed sha256
 *     blocks and yields chunks as a \Generator so tests can drain without real sockets or sleeps.
 *
 * Block model: content is a sequence of fixed {@see BLOCK}-byte blocks; block k is a pure function
 * of (seed, label, k). Because a byte's value depends only on its absolute offset (never on how
 * much was emitted before it), any Range is O(1): {@see bytesAt()} computes only the blocks that
 * span the requested window. Same (seed,label) => identical bytes forever (coherent on revisit,
 * survives dedup); a new label => fresh content (novelty-on-advance).
 */
final class SeededStream
{
    /** One block. 4 KiB matches FakeSecrets/DownloadRouter's block granularity; memory is O(BLOCK). */
    public const BLOCK = 4096;

    /**
     * The generated bytes of the logical artifact (seed,label) over the window [offset, offset+len).
     * Pure and total: O($len + BLOCK) memory and O($len) time regardless of $offset — the key at
     * "line 1.4M" is served without fabricating the preceding 1.4M bytes. Deterministic in the
     * absolute offset, so overlapping ranges agree byte-for-byte (Range = whole are consistent).
     */
    public function bytesAt(int $seed, string $label, int $offset, int $len): string
    {
        if ($len <= 0 || $offset < 0) {
            return '';
        }
        $firstBlock = intdiv($offset, self::BLOCK);
        $lastBlock = intdiv($offset + $len - 1, self::BLOCK);
        $buf = '';
        for ($k = $firstBlock; $k <= $lastBlock; $k++) {
            $buf .= $this->block($seed, $label, $k);
        }

        return substr($buf, $offset - $firstBlock * self::BLOCK, $len);
    }

    /**
     * One 4 KiB block, deterministic in (seed,label,k). base64 of hash-chained sha256 (ASCII, no
     * CR/LF — size- and CRLF-safe for any transport), exactly the FakeSecrets::chars / DownloadRouter
     * ::fill idiom. Memory is O(BLOCK): the block is built and returned, never an accumulated artifact.
     */
    public function block(int $seed, string $label, int $k): string
    {
        $key = $seed . '|' . $label . '|' . $k;
        $out = '';
        $i = 0;
        while (strlen($out) < self::BLOCK) {
            $out .= base64_encode(hash('sha256', $key . '|' . $i, true));
            $i++;
        }

        return substr($out, 0, self::BLOCK);
    }

    /**
     * Yield formatted chunks of the artifact up to a hard byte cap. $blockFn shapes each block's raw
     * bytes into the artifact's skin (a log line, an .env line, a token-hostile record — 0245b/c);
     * the default {@see rawBlock} passes the raw filler through. A \Generator so tests drain it
     * summing strlen() and DISCARDING each chunk — the honest O(block) memory measurement, never a
     * StreamEmitter whose captured buffer would itself grow with the output.
     *
     * @param callable(int,string):string|null $blockFn (blockIndex, rawBlockBytes) => formatted bytes
     * @return \Generator<int,string>
     */
    public function chunks(int $seed, string $label, int $capBytes, ?callable $blockFn = null): \Generator
    {
        if ($capBytes <= 0) {
            return;
        }
        $blockFn ??= self::rawBlock();
        $sent = 0;
        $k = 0;
        $emptyStreak = 0;
        while ($sent < $capBytes) {
            $piece = (string) $blockFn($k, $this->block($seed, $label, $k));
            $k++;
            if ($piece === '') {
                // A formatter may legitimately emit nothing for some block index; bail out of a
                // pathological all-empty formatter rather than spin forever (the byte cap can't bind
                // if no bytes are produced).
                if (++$emptyStreak >= 64) {
                    return;
                }
                continue;
            }
            $emptyStreak = 0;
            if ($sent + strlen($piece) > $capBytes) {
                $piece = substr($piece, 0, $capBytes - $sent);
            }
            yield $piece;
            $sent += strlen($piece);
        }
    }

    /**
     * Stream a generated artifact through the emitter, honouring the byte cap and $aborted (the
     * client hung up — stop fabricating). Returns the bytes actually emitted, for the budget ledger.
     * $aborted is injectable so tests can exercise the hang-up path without a real socket; it
     * defaults to the real connection_aborted().
     *
     * @param callable(int,string):string|null $blockFn
     * @param callable():int|null               $aborted
     */
    public function stream(StreamEmitter $e, int $seed, string $label, int $capBytes, ?callable $blockFn = null, ?callable $aborted = null): int
    {
        $aborted ??= static fn (): int => connection_aborted();
        $sent = 0;
        foreach ($this->chunks($seed, $label, $capBytes, $blockFn) as $chunk) {
            $e->chunk($chunk);
            $sent += strlen($chunk);
            if ($aborted() !== 0) {
                break;
            }
        }

        return $sent;
    }

    /** The identity formatter: emit the raw block filler unchanged. */
    public static function rawBlock(): callable
    {
        return static fn (int $k, string $raw): string => $raw;
    }
}
