<?php

declare(strict_types=1);

namespace Funnypot\App\Service;

use RuntimeException;

/**
 * Renders the profile's chosen nginx aliases into fixed `listen` includes. It accepts only joined
 * nginx-alias endpoint objects and emits canonical `listen <port>[ ssl];` lines in port order — no
 * operator text ever reaches nginx. Canonical 80/443 stay literal in demo/nginx.conf and are never
 * rendered here. The full configuration is validated with `nginx -t` before nginx starts.
 */
final class NginxProfileRenderer
{
    /**
     * @param list<ServiceEndpoint> $endpoints selected nginx-alias endpoints
     * @return array{0:string,1:string} [http fragment bytes, https fragment bytes]
     */
    public static function render(array $endpoints): array
    {
        $http = [];
        $https = [];
        foreach ($endpoints as $ep) {
            if (!$ep->isNginxAlias()) {
                throw new RuntimeException('nginx renderer: endpoint ' . $ep->endpointId . ' is not an nginx alias');
            }
            if ($ep->containerPort === 80 || $ep->containerPort === 443) {
                throw new RuntimeException('nginx renderer: canonical 80/443 are literal, never rendered');
            }
            if ($ep->tls) {
                $https[$ep->containerPort] = true;
            } else {
                $http[$ep->containerPort] = true;
            }
        }
        ksort($http);
        ksort($https);

        return [self::fragment(array_keys($http), false), self::fragment(array_keys($https), true)];
    }

    /** @param list<int> $ports */
    private static function fragment(array $ports, bool $ssl): string
    {
        $lines = ['# generated by funnypot services:prepare — do not edit'];
        foreach ($ports as $port) {
            $lines[] = 'listen ' . $port . ($ssl ? ' ssl' : '') . ';';
        }

        return implode("\n", $lines) . "\n";
    }
}
