<?php

declare(strict_types=1);

// GENERATED by `funnypot compile-protocols` — DO NOT EDIT.

return array (
  'clamav' => 
  array (
    'listen' => 
    array (
      0 => 3310,
    ),
    'severity' => 'medium',
    'tags' => 
    array (
      0 => 'protocol',
      1 => 'clamav',
      2 => 'antivirus',
    ),
    'banner' => '',
    'framing' => 'raw',
    'rules' => 
    array (
      0 => 
      array (
        'match' => 
        array (
          'prefix' => 'VERSION',
        ),
        'send' => 'ClamAV 0.103.2/26857/Sun Aug 16 08:00:00 2026
',
      ),
      1 => 
      array (
        'match' => 
        array (
          'prefix' => 'PING',
        ),
        'send' => 'PONG
',
      ),
    ),
    'default' => 
    array (
      'send' => 'UNKNOWN COMMAND
',
    ),
  ),
  'ethernet-ip' => 
  array (
    'listen' => 
    array (
      0 => 44818,
    ),
    'severity' => 'medium',
    'tags' => 
    array (
      0 => 'protocol',
      1 => 'ethernet-ip',
      2 => 'enip',
      3 => 'cip',
      4 => 'ics',
      5 => 'scada',
      6 => 'plc',
      7 => 'allen-bradley',
      8 => 'rockwell',
    ),
    'banner' => '',
    'framing' => 'raw',
    'rules' => 
    array (
      0 => 
      array (
        'match' => 
        array (
          'prefix' => 'c' . "\0" . '',
        ),
        'send' => '{{hex:63003f00000000000000000000000000000000000000000001000c00390001000002af1200000000000000000000000001000e003600140b60311a066c0017}}1769-L35E Ethernet Port{{hex:ff}}',
      ),
    ),
    'default' => NULL,
  ),
  'finger' => 
  array (
    'listen' => 
    array (
      0 => 79,
    ),
    'severity' => 'medium',
    'tags' => 
    array (
      0 => 'protocol',
      1 => 'finger',
      2 => 'discovery',
    ),
    'banner' => '',
    'framing' => 'line',
    'rules' => 
    array (
      0 => 
      array (
        'match' => 
        array (
          'equals' => '',
        ),
        'send' => 'Node        User        Action     Idle    Login Time
%%HOST%%root        login      00:12   Aug 18 09:14
%%HOST%%admin       idle       02:04   Aug 18 08:02
',
      ),
    ),
    'default' => 
    array (
      'send' => 'Node        User        Action     Idle    Login Time
%%HOST%%?           no such user
',
    ),
  ),
  'ftp' => 
  array (
    'listen' => 
    array (
      0 => 21,
    ),
    'severity' => 'medium',
    'tags' => 
    array (
      0 => 'protocol',
      1 => 'ftp',
    ),
    'banner' => '220 (vsFTPd 3.0.5)
',
    'framing' => 'line',
    'rules' => 
    array (
      0 => 
      array (
        'match' => 
        array (
          'prefix' => 'USER',
        ),
        'send' => '331 Please specify the password.
',
      ),
      1 => 
      array (
        'match' => 
        array (
          'prefix' => 'PASS',
        ),
        'send' => '230 Login successful.
',
      ),
      2 => 
      array (
        'match' => 
        array (
          'prefix' => 'SYST',
        ),
        'send' => '215 UNIX Type: L8
',
      ),
      3 => 
      array (
        'match' => 
        array (
          'prefix' => 'FEAT',
        ),
        'send' => '211-Features:
 PASV
 UTF8
211 End
',
      ),
      4 => 
      array (
        'match' => 
        array (
          'prefix' => 'PWD',
        ),
        'send' => '257 "/" is the current directory
',
      ),
      5 => 
      array (
        'match' => 
        array (
          'prefix' => 'TYPE',
        ),
        'send' => '200 Switching to Binary mode.
',
      ),
      6 => 
      array (
        'match' => 
        array (
          'regex' => '^(LIST|NLST|MLSD)\\b',
        ),
        'send' => '150 Here comes the directory listing.
226 Directory send OK.
',
      ),
      7 => 
      array (
        'match' => 
        array (
          'prefix' => 'QUIT',
        ),
        'send' => '221 Goodbye.
',
        'close' => true,
      ),
    ),
    'default' => 
    array (
      'send' => '500 Unknown command.
',
    ),
  ),
  'imap' => 
  array (
    'listen' => 
    array (
      0 => 143,
    ),
    'severity' => 'medium',
    'tags' => 
    array (
      0 => 'protocol',
      1 => 'imap',
      2 => 'mail',
    ),
    'banner' => '* OK IMAP4rev1 Service Ready
',
    'framing' => 'line',
    'rules' => 
    array (
      0 => 
      array (
        'match' => 
        array (
          'contains' => 'CAPABILITY',
        ),
        'send' => '* CAPABILITY IMAP4rev1 AUTH=PLAIN LOGIN-REFERRALS
* OK CAPABILITY completed
',
      ),
      1 => 
      array (
        'match' => 
        array (
          'contains' => 'LOGIN',
        ),
        'send' => '* OK LOGIN completed
',
      ),
      2 => 
      array (
        'match' => 
        array (
          'contains' => 'SELECT',
        ),
        'send' => '* 0 EXISTS
* 0 RECENT
* OK [UIDVALIDITY 1] UIDs valid
* OK [READ-WRITE] SELECT completed
',
      ),
      3 => 
      array (
        'match' => 
        array (
          'contains' => 'LIST',
        ),
        'send' => '* LIST () "/" "INBOX"
* OK LIST completed
',
      ),
      4 => 
      array (
        'match' => 
        array (
          'contains' => 'NOOP',
        ),
        'send' => '* OK NOOP completed
',
      ),
      5 => 
      array (
        'match' => 
        array (
          'contains' => 'LOGOUT',
        ),
        'send' => '* BYE IMAP4rev1 Server logging out
* OK LOGOUT completed
',
        'close' => true,
      ),
    ),
    'default' => 
    array (
      'send' => '* BAD Command unrecognized
',
    ),
  ),
  'memcached' => 
  array (
    'listen' => 
    array (
      0 => 11211,
    ),
    'severity' => 'medium',
    'tags' => 
    array (
      0 => 'protocol',
      1 => 'memcached',
      2 => 'cache',
    ),
    'banner' => '',
    'framing' => 'line',
    'rules' => 
    array (
      0 => 
      array (
        'match' => 
        array (
          'equals' => 'version',
        ),
        'send' => 'VERSION 1.6.21
',
      ),
      1 => 
      array (
        'match' => 
        array (
          'prefix' => 'stats',
        ),
        'send' => 'STAT pid 1
STAT version 1.6.21
STAT uptime 824113
STAT curr_connections 1
STAT curr_items 0
END
',
      ),
      2 => 
      array (
        'match' => 
        array (
          'prefix' => 'get',
        ),
        'send' => 'END
',
      ),
      3 => 
      array (
        'match' => 
        array (
          'regex' => '^(set|add|replace)\\b',
        ),
        'send' => 'STORED
',
      ),
      4 => 
      array (
        'match' => 
        array (
          'prefix' => 'quit',
        ),
        'send' => '',
        'close' => true,
      ),
    ),
    'default' => 
    array (
      'send' => 'ERROR
',
    ),
  ),
  'modbus' => 
  array (
    'listen' => 
    array (
      0 => 502,
    ),
    'severity' => 'medium',
    'tags' => 
    array (
      0 => 'protocol',
      1 => 'modbus',
      2 => 'ics',
      3 => 'scada',
      4 => 'plc',
      5 => 'schneider',
      6 => 'modicon',
    ),
    'banner' => '',
    'framing' => 'raw',
    'rules' => 
    array (
      0 => 
      array (
        'match' => 
        array (
          'contains' => '+',
        ),
        'send' => '{{hex:000000000031002b0e02830000030012}}Schneider Electric{{hex:010c}}BMX P34 2020{{hex:0205}}V2.60',
      ),
      1 => 
      array (
        'match' => 
        array (
          'contains' => 'Z' . "\0" . '',
        ),
        'send' => '{{hex:000100000025005a00000000}}BMX P34 2020{{hex:00}}Schneider Electric',
      ),
    ),
    'default' => NULL,
  ),
  'mongodb' => 
  array (
    'listen' => 
    array (
      0 => 27017,
    ),
    'severity' => 'medium',
    'tags' => 
    array (
      0 => 'protocol',
      1 => 'mongodb',
      2 => 'mongo',
      3 => 'database',
      4 => 'db',
      5 => 'nosql',
    ),
    'banner' => '',
    'framing' => 'raw',
    'rules' => 
    array (
    ),
    'default' => 
    array (
      'send' => '{{hex:f80000002a00000000000000010000000000000000000000000000000000000001000000d400000008}}ismaster{{hex:000102}}version{{hex:0007000000}}7.0.30{{hex:0010}}maxBsonObjectSize{{hex:000000000110}}maxMessageSizeBytes{{hex:00006cdc0210}}maxWriteBatchSize{{hex:00a086010009}}localTime{{hex:00009418d18f01000010}}minWireVersion{{hex:000000000010}}maxWireVersion{{hex:001500000008}}readOnly{{hex:000010}}totalLinesWritten{{hex:000400000001}}ok{{hex:00000000000000f03f00}}',
    ),
  ),
  'mysql' => 
  array (
    'listen' => 
    array (
      0 => 3306,
    ),
    'severity' => 'medium',
    'tags' => 
    array (
      0 => 'protocol',
      1 => 'mysql',
      2 => 'database',
      3 => 'db',
    ),
    'banner' => '{{hex:4a0000000a}}8.0.36{{hex:002d0000003f1a552c6014770800ffffff0200ffdf1500000000000000000000412d6b1952337e116428504600}}mysql_native_password{{hex:00}}',
    'framing' => 'raw',
    'rules' => 
    array (
    ),
    'default' => NULL,
  ),
  'pop3' => 
  array (
    'listen' => 
    array (
      0 => 110,
    ),
    'severity' => 'medium',
    'tags' => 
    array (
      0 => 'protocol',
      1 => 'pop3',
      2 => 'mail',
    ),
    'banner' => '+OK POP3 server (Dovecot) ready.
',
    'framing' => 'line',
    'rules' => 
    array (
      0 => 
      array (
        'match' => 
        array (
          'prefix' => 'USER',
        ),
        'send' => '+OK
',
      ),
      1 => 
      array (
        'match' => 
        array (
          'prefix' => 'PASS',
        ),
        'send' => '+OK Logged in.
',
      ),
      2 => 
      array (
        'match' => 
        array (
          'prefix' => 'STAT',
        ),
        'send' => '+OK 0 0
',
      ),
      3 => 
      array (
        'match' => 
        array (
          'prefix' => 'LIST',
        ),
        'send' => '+OK 0 messages (0 octets)
.
',
      ),
      4 => 
      array (
        'match' => 
        array (
          'prefix' => 'UIDL',
        ),
        'send' => '+OK
.
',
      ),
      5 => 
      array (
        'match' => 
        array (
          'prefix' => 'RETR',
        ),
        'send' => '-ERR no such message
',
      ),
      6 => 
      array (
        'match' => 
        array (
          'prefix' => 'DELE',
        ),
        'send' => '-ERR no such message
',
      ),
      7 => 
      array (
        'match' => 
        array (
          'prefix' => 'CAPA',
        ),
        'send' => '+OK Capability list follows
USER
UIDL
TOP
.
',
      ),
      8 => 
      array (
        'match' => 
        array (
          'prefix' => 'NOOP',
        ),
        'send' => '+OK
',
      ),
      9 => 
      array (
        'match' => 
        array (
          'prefix' => 'RSET',
        ),
        'send' => '+OK
',
      ),
      10 => 
      array (
        'match' => 
        array (
          'prefix' => 'QUIT',
        ),
        'send' => '+OK Logging out.
',
        'close' => true,
      ),
    ),
    'default' => 
    array (
      'send' => '-ERR unknown command
',
    ),
  ),
  'postgresql' => 
  array (
    'listen' => 
    array (
      0 => 5432,
    ),
    'severity' => 'medium',
    'tags' => 
    array (
      0 => 'protocol',
      1 => 'postgresql',
      2 => 'postgres',
      3 => 'database',
      4 => 'db',
    ),
    'banner' => '',
    'framing' => 'raw',
    'rules' => 
    array (
    ),
    'default' => 
    array (
      'send' => 'R{{hex:000000170000000a}}SCRAM-SHA-256{{hex:0000}}S{{hex:00000018}}server_version{{hex:00}}16.2{{hex:00}}S{{hex:00000019}}client_encoding{{hex:00}}UTF8{{hex:00}}S{{hex:00000019}}integer_datetimes{{hex:00}}on{{hex:00}}T{{hex:0000007b0004}}Name{{hex:0000000000000000000019ffffffffffff0000}}Owner{{hex:0000000000000000000019ffffffffffff0000}}Locale Provider{{hex:0000000000000000000019ffffffffffff0000}}Access privileges{{hex:0000000000000000000019ffffffffffff0000}}',
    ),
  ),
  'redis' => 
  array (
    'listen' => 
    array (
      0 => 6379,
    ),
    'severity' => 'medium',
    'tags' => 
    array (
      0 => 'protocol',
      1 => 'redis',
      2 => 'cache',
    ),
    'banner' => '',
    'framing' => 'resp',
    'rules' => 
    array (
      0 => 
      array (
        'match' => 
        array (
          'equals' => 'PING',
        ),
        'send' => '+PONG
',
      ),
      1 => 
      array (
        'match' => 
        array (
          'prefix' => 'AUTH',
        ),
        'send' => '+OK
',
      ),
      2 => 
      array (
        'match' => 
        array (
          'prefix' => 'INFO',
        ),
        'send' => 
        array (
          'bulk' => '# Server
redis_version:7.2.4
redis_mode:standalone
os:Linux 5.15.0 x86_64
arch_bits:64
process_id:1
run_id:{{fake.redis_runid:hex:40}}
tcp_port:6379
uptime_in_seconds:824113
# Clients
connected_clients:1
# Memory
used_memory_human:1.02M
maxmemory_human:0B
# Keyspace
db0:keys=3,expires=0,avg_ttl=0',
        ),
      ),
      3 => 
      array (
        'match' => 
        array (
          'prefix' => 'CONFIG GET',
        ),
        'send' => 
        array (
          'bulk_array' => 
          array (
            0 => 'dir',
            1 => '/var/lib/redis',
          ),
        ),
      ),
      4 => 
      array (
        'match' => 
        array (
          'prefix' => 'COMMAND',
        ),
        'send' => '*0
',
      ),
      5 => 
      array (
        'match' => 
        array (
          'prefix' => 'SELECT',
        ),
        'send' => '+OK
',
      ),
      6 => 
      array (
        'match' => 
        array (
          'prefix' => 'CLIENT',
        ),
        'send' => '+OK
',
      ),
      7 => 
      array (
        'match' => 
        array (
          'regex' => '^(GET|SET|DEL|KEYS|SCAN|HGETALL|LRANGE|TYPE|TTL|EXISTS)\\b',
        ),
        'send' => '$-1
',
      ),
      8 => 
      array (
        'match' => 
        array (
          'prefix' => 'QUIT',
        ),
        'send' => '+OK
',
        'close' => true,
      ),
    ),
    'default' => 
    array (
      'send' => '-ERR unknown command
',
    ),
  ),
  'rsync' => 
  array (
    'listen' => 
    array (
      0 => 873,
    ),
    'severity' => 'medium',
    'tags' => 
    array (
      0 => 'protocol',
      1 => 'rsync',
      2 => 'sync',
    ),
    'banner' => '@RSYNCD: 31.0
',
    'framing' => 'line',
    'rules' => 
    array (
      0 => 
      array (
        'match' => 
        array (
          'prefix' => '@RSYNCD',
        ),
        'send' => '@ERROR: protocol startup error (bad session)
',
        'close' => true,
      ),
    ),
    'default' => 
    array (
      'send' => '@ERROR: protocol startup error (bad session)
',
    ),
  ),
  'sip' => 
  array (
    'listen' => 
    array (
      0 => 5060,
    ),
    'severity' => 'medium',
    'tags' => 
    array (
      0 => 'protocol',
      1 => 'sip',
      2 => 'voip',
      3 => 'pbx',
      4 => 'asterisk',
    ),
    'banner' => '',
    'framing' => 'raw',
    'rules' => 
    array (
      0 => 
      array (
        'match' => 
        array (
          'regex' => '^(OPTIONS|REGISTER|INVITE|ACK|BYE|CANCEL)',
        ),
        'send' => '',
      ),
    ),
    'default' => 
    array (
      'send' => '',
    ),
  ),
  'smtp' => 
  array (
    'listen' => 
    array (
      0 => 25,
    ),
    'severity' => 'medium',
    'tags' => 
    array (
      0 => 'protocol',
      1 => 'smtp',
      2 => 'mail',
    ),
    'banner' => '220 mail.example.com ESMTP Postfix (Ubuntu)
',
    'framing' => 'line',
    'rules' => 
    array (
      0 => 
      array (
        'match' => 
        array (
          'prefix' => 'EHLO',
        ),
        'send' => '250-mail.example.com
250-PIPELINING
250-SIZE 10240000
250 8BITMIME
',
      ),
      1 => 
      array (
        'match' => 
        array (
          'prefix' => 'HELO',
        ),
        'send' => '250 mail.example.com
',
      ),
      2 => 
      array (
        'match' => 
        array (
          'prefix' => 'MAIL',
        ),
        'send' => '250 2.1.0 Ok
',
      ),
      3 => 
      array (
        'match' => 
        array (
          'prefix' => 'RCPT',
        ),
        'send' => '250 2.1.5 Ok
',
      ),
      4 => 
      array (
        'match' => 
        array (
          'prefix' => 'DATA',
        ),
        'send' => '354 End data with <CR><LF>.<CR><LF>
',
      ),
      5 => 
      array (
        'match' => 
        array (
          'prefix' => 'RSET',
        ),
        'send' => '250 2.0.0 Ok
',
      ),
      6 => 
      array (
        'match' => 
        array (
          'prefix' => 'NOOP',
        ),
        'send' => '250 2.0.0 Ok
',
      ),
      7 => 
      array (
        'match' => 
        array (
          'prefix' => 'QUIT',
        ),
        'send' => '221 2.0.0 Bye
',
        'close' => true,
      ),
    ),
    'default' => 
    array (
      'send' => '502 5.5.2 Error: command not recognized
',
    ),
  ),
  'ssh' => 
  array (
    'listen' => 
    array (
      0 => 2222,
    ),
    'severity' => 'medium',
    'tags' => 
    array (
      0 => 'protocol',
      1 => 'ssh',
      2 => 'banner',
    ),
    'banner' => 'SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.6
',
    'framing' => 'raw',
    'rules' => 
    array (
      0 => 
      array (
        'match' => 
        array (
          'regex' => '^SSH-',
        ),
        'send' => '',
        'close' => true,
      ),
    ),
    'default' => 
    array (
      'send' => '',
    ),
  ),
  'telnet' => 
  array (
    'listen' => 
    array (
      0 => 23,
    ),
    'severity' => 'medium',
    'tags' => 
    array (
      0 => 'protocol',
      1 => 'telnet',
      2 => 'shell',
    ),
    'banner' => '
Ubuntu 22.04.3 LTS
web01 login: ',
    'framing' => 'line',
    'rules' => 
    array (
    ),
    'default' => NULL,
    'shell' => 
    array (
      'hostname' => 'web01',
      'home' => '/root',
      'password_prompt' => 'Password: ',
      'reject_attempts' => 0,
      'motd' => '
Welcome to Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-91-generic x86_64)

',
    ),
  ),
  'vnc' => 
  array (
    'listen' => 
    array (
      0 => 5900,
    ),
    'severity' => 'medium',
    'tags' => 
    array (
      0 => 'protocol',
      1 => 'vnc',
      2 => 'remote-access',
    ),
    'banner' => 'RFB 003.008
',
    'framing' => 'raw',
    'rules' => 
    array (
      0 => 
      array (
        'match' => 
        array (
          'regex' => '^RFB',
        ),
        'send' => '',
        'close' => true,
      ),
    ),
    'default' => 
    array (
      'send' => '',
    ),
  ),
  'zookeeper' => 
  array (
    'listen' => 
    array (
      0 => 2181,
    ),
    'severity' => 'medium',
    'tags' => 
    array (
      0 => 'protocol',
      1 => 'zookeeper',
      2 => 'exposure',
    ),
    'banner' => '',
    'framing' => 'line',
    'rules' => 
    array (
      0 => 
      array (
        'match' => 
        array (
          'prefix' => 'ruok',
        ),
        'send' => 'imok
',
        'close' => true,
      ),
      1 => 
      array (
        'match' => 
        array (
          'prefix' => 'envi',
        ),
        'send' => 'Environment:
zookeeper.version=3.8.3-5db9d4e3e05a5d2caa2ee9d8fb0a4419ee80979d, built on 2023-10-05 12:34 UTC
host.name=zk1
java.version=11.0.20
java.vendor=Eclipse Adoptium
java.home=/usr/lib/jvm/temurin-11-jdk
os.name=Linux
os.arch=amd64
os.version=5.15.0-91-generic
user.name=zookeeper
user.dir=/',
        'close' => true,
      ),
      2 => 
      array (
        'match' => 
        array (
          'prefix' => 'stat',
        ),
        'send' => 'Zookeeper version: 3.8.3-5db9d4e3e05a5d2caa2ee9d8fb0a4419ee80979d, built on 2023-10-05 12:34 UTC
Clients:
 /127.0.0.1:52344[0](queued=0,recved=1,sent=0)

Latency min/avg/max: 0/0/12
Received: 41
Sent: 40
Connections: 1
Outstanding: 0
Zxid: 0x100000042
Mode: standalone
Node count: 128',
        'close' => true,
      ),
    ),
    'default' => 
    array (
      'send' => 'This ZooKeeper instance is not currently serving requests.
',
    ),
  ),
);
